### PR TITLE
Replaced the amt and rtm and merge as one called exo

### PR DESCRIPTION
**Pull request by poldz123**
Amt and Rtm transit is one transit but for some reason, both were added which resulted in duplicated data.

Now they are merged as one and now called exo: https://exo.quebec/en/about/open-data

### CODE REVIEW

**Comment by poldz123** [comment]
@drewda Not sure about the workflow error, can you guide me about it?

**Comment by drewda** [comment]
@poldz123 looks good. thank you for all of these edits.

**Comment by poldz123** [comment]
@drewda A follow up on this question: https://github.com/transitland/transitland-atlas/pull/80#issuecomment-665519753

Why is the Wroute is still in the datastore, should it be already removed from it?

**Comment by poldz123** [comment]
@drewda Seems that the changes on this does not reflect in the feed registry in transit land: https://transit.land/feed-registry/?country=CA

**Pull request merged**
