### PR TITLE
zenbus

### PR DESCRIPTION
**Pull request by aquaticpotato3677**

### CODE REVIEW

**Comment by aquaticpotato3677** [comment]
plenty of French Zenbus links [here](https://transport.data.gouv.fr/datasets?locale=en&q=zenbus&type=public-transit)
it, uh, might take me a bit to get them all in here

**Comment by drewda** [comment]
@aquaticpotato3677 thanks for working through so many Zenbus feeds. Your choice whether to complete all in this PR or do multiple PRs.

**Comment by aquaticpotato3677** [comment]
fixed a few gtfs ids in `f-sp9x-normandie` but also left a few confusing ones alone...

**Comment by aquaticpotato3677** [comment]
the higher quality (has shapes) zenbus gtfs file and realtime tracking only have the school routes, so using another gtfs file

**Comment by drewda** [comment]
@aquaticpotato3677 thanks for so many additions!

**Pull request merged**
