### PR TITLE
Create dubaipulse.gov.ae.dmfr.json

### PR DESCRIPTION
**Pull request by pleitman**
New proposed file for static-gtfs from Dubai Roads & Transport Authority (RTA). GTFS file hosted on Dubai Pulse, the city's open data platform.

This is my first request for an addition to the transitland data. I'd appreciate someone to review and verify the contents are good.

Also, note that the file source is a .7z file, not .zip. Is this a problem?

### CODE REVIEW

**Comment by drewda** [comment]
Hi @pleitman thanks for your contribution. [transitland-lib](https://github.com/interline-io/transitland-lib) can only work with ZIP files, as this is required by the GTFS spec. We will look into ways to convert this 7z archive to a zip archive.

**Comment by drewda** [comment]
We've set up a script to convert this to a normal zip archive. For now it needs to be run manually, but if this feed is updated on a regular basis, we can set up the script to run on an automatic ongoing basis.

Thanks again for this contribution and we always welcome more!

**Comment by pleitman** [comment]
Thanks, dewda. If it helps, I've noticed this GTFS dataset has been updated approximately once per month (or at least since I discovered it in March it seems to have been updated on a monthly basis).

Am I required to do anything else at this point? Should I create a pull request to create the operator for this feed?

**Comment by pleitman** [comment]
@drewda, I just wanted to confirm there was nothing further for me to do on this related to this (see my comment above).

Thanks again for your help.

**Comment by drewda** [comment]
@pleitman no more steps required at this point.

An operator record is automatically created. It's only necessary to create an operator file if you want to add extra metadata or group together more than one feed.

Thanks again for your contribution.

**Pull request merged**
