### PR TITLE
Create dpmo.cz.dmfr.json

### PR DESCRIPTION
**Pull request by Peperman66**

### CODE REVIEW

**Comment by Peperman66** [comment]
By the way, are the onestop id's good enough or should they be longer, including full names of the operator or feed provider?

**Comment by drewda** [comment]
@Peperman66 thank you for this contribution. Those Onestop IDs look good. If you include the geohash component it is fine to have a short name. If you skip the geohash component, we aim to have a longer and more descriptive name.

**Comment by drewda** [comment]
This will be ready to merge after its formatting is adjusted. To do so either run `transitland dmfr format --save feeds/dpmo.cz.dmfr.json` or mark the PR as ready for review and myself or another maintainer can apply the "opinionated format"

**Comment by Peperman66** [comment]
I tried changing the spacing so now it should pass the tests

**Pull request merged**
