### PR TITLE
Create rejseplanen.dk.dmfr.json

### PR DESCRIPTION
**Pull request by akaise21**
I used the Samtrafiken file as a template, as I couldn't find the example file. For now, I've just added the data provider as the operator. Should I add all operators/agencies instead? They are included in the GTFS file, so using those instead would make it easier to create and maintain them. Thanks!

### CODE REVIEW

**Comment by drewda** [comment]
@akaise21 in this case I would recommend having no operator listing.

When the Transitland platform imports the feed, it will automatically detect the agencies and create "virtual" operator listings for all them.

It's only necessary to create operator listings in the Atlas when you want to add extra information (like a short name or tags) or to group togther multiple feeds (like one static GTFS and one GTFS Realtime feed for the same operator).

**Comment by akaise21** [comment]
Thanks @drewda, got it! I've removed the operator in the newest commit :)

**Comment by drewda** [comment]
thanks for your contribution!

**Comment by akaise21** [comment]
Thanks for the fix ;)

**Pull request merged**
