### PR TITLE
Add Swiftly's GTFS-rt feeds for RTA Maryland

### PR DESCRIPTION
**Pull request by ericouyang**
Reopening #62 to create a DMFR.json file for Swiftly-provided realtime information

### CODE REVIEW

**Comment by ericouyang** [comment]
@drewda - Just a friendly ping on this PR. Let me know if any changes should be made before merging.

**Comment by ericouyang** [comment]
Hi @drewda - Thanks for merging these changes. I was expecting that once merged, that these realtime feeds would show up on this page, but it seems to only show the static GTFS data. 

https://transit.land/feed-registry/operators/o-dqcq-regionaltransportationagencyofcentralmaryland

Do you have any suggestions on how to fix that?

**Comment by drewda** [comment]
@ericouyang good question. That's a side effect of the Transitland v1-to-v2 migration we are currently in the middle of.

You can find the new feeds in all the APIs, including http://transit.land/api/v1/feeds/f-dqcq-regionaltransportationagencyofcentralmaryland~rt

When we release the Transitland v2 website it will be able to use the new feed/operator associations that are happening behind the scenes.

**Comment by ericouyang** [comment]
Thanks, @drewda, for that information. Do you have a timeframe for when you expect that migration to be completed? For us, the public webpage to look up feeds is the most important spot where we'd like to make sure the feeds are visible. Is there a different process for updating the website? 

I noticed that this PR seems to be the one that's referenced to port all the feeds from V1 to V2, but it's been open in draft state for a while: https://github.com/transitland/transitland-atlas/pull/43/files

**Pull request merged**
