### PR TITLE
Update data.gouv.fr.dmfr.json

### PR DESCRIPTION
**Pull request by kalon33**
Add one regional feed for Normandy, infos are based on agency.txt from the GTFS.

### CODE REVIEW

**Comment by kalon33** [comment]
Dear @drewda, would it be possible to have a look at this? In order to know if it's OK or if I should make some changes?

Thanks a lot for your help. Have a nice weekend.

**Comment by drewda** [comment]
Hi @kalon33, thanks for these contributions. We do not have French speakers/readers in our office, so it is great to have assistance improving Transitland Atlas's coverage of French feeds. I will be glad to have a look and let you know shortly of any issues.

**Comment by kalon33** [comment]
@drewda you're welcome, thanks a lot for your help for correcting, explaining what to do, and merging these! Is this one mergeable or should I change some things?

**Comment by drewda** [comment]
@kalon33 this was just a matter of applying the "opinionated" DMFR format, which is required by our GitHub Actions checks.

**Comment by kalon33** [comment]
@drewda thanks a lot! How often are the feeds then parsed and added to the map and API?

**Comment by drewda** [comment]
@kalon33 feeds are usually fetched and imported every few hours. Map tiles are usually rebuilt daily.

**Comment by kalon33** [comment]
@drewda thanks again! Do you know some way to make a dynamic live map from these data?

**Pull request merged**
