### PR TITLE
Update metrotas.com.au.dmfr.json

### PR DESCRIPTION
**Pull request by martiandeath**
Added two additional URLs for Metro Tasmania as they have three current URLs for different parts of the state (the added URLs also include new operators Lee's Coaches, Manion's Coaches, Calow's Coaches, East Tamar Bus Lines and Mersey Link, as well as Redline Coaches and Tassielink, which were already in the exisiting URL)

### CODE REVIEW

**Comment by drewda** [comment]
@martiandeath thanks for this contribution.

The DMFR format cannot take more than one current static URL for a single feed record. The pattern to use instead is to create a separate feed record (with a separate feed Onestop ID) for each one of the current static feed URLs.

**Comment by martiandeath** [comment]
Good to know, I'll see if I can figure that out later today, cheers

**Comment by martiandeath** [comment]
@drewda I think I have modified it correctly this time, let me know if something is wrong

**Comment by drewda** [comment]
@martiandeath thanks for revising!

I've made a few edits to retain existing Onestop IDs (to be more stable for Transitland's users).

Will go ahead and merge this now.

**Pull request merged**
